theme: jekyll-theme-slate
title: The homepage of Noricious, mere student
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://noricious.github.io/"
markdown: kramdown
